#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service() {
    . /usr/lib/portalwrt/defaults.sh
    portal_theme
    procd_open_instance
    procd_set_param command /usr/libexec/portal-background watch
    procd_set_param respawn
    procd_close_instance
}
service_triggers() {
    procd_add_reload_trigger luci kucat argon
}
